import type {
  Asset,
  DatabaseShape,
  Note,
  Template,
  WorkshopPreset,
} from "./types.js";

const now = () => new Date().toISOString();

const templates: Template[] = [
  {
    id: "botanical-reflection",
    name: "Botanical Reflection",
    summary: "Soft parchment, olive accents, and layered editorial spacing.",
    accentColor: "#5b6450",
    texture: "Pressed vellum",
    uses: 1240,
    featured: true,
    previewImage: "https://picsum.photos/seed/litenote-template-1/720/960",
  },
  {
    id: "monochrome-focus",
    name: "Monochrome Focus",
    summary: "High-contrast minimal layout for research notes and sprint logs.",
    accentColor: "#2f3338",
    texture: "Smooth cotton",
    uses: 830,
    featured: false,
    previewImage: "https://picsum.photos/seed/litenote-template-2/720/540",
  },
  {
    id: "golden-hour",
    name: "Golden Hour Aura",
    summary: "Warm gradients and framed callouts for reflective long-form entries.",
    accentColor: "#86603d",
    texture: "Sun-faded paper",
    uses: 965,
    featured: false,
    previewImage: "https://picsum.photos/seed/litenote-template-3/720/540",
  },
];

const assets: Asset[] = [
  {
    id: "asset-parchment",
    name: "Raw Parchment II",
    category: "Texture",
    creator: "Elena Vass",
    likes: 1200,
    description: "Organic paper grain for hero blocks and note cards.",
    image: "https://picsum.photos/seed/litenote-asset-1/480/620",
  },
  {
    id: "asset-flora",
    name: "Wildwood Flora Set",
    category: "Illustration",
    creator: "Julian Thorne",
    likes: 845,
    description: "Ink-drawn botanical marks for stickers, dividers, and quotes.",
    image: "https://picsum.photos/seed/litenote-asset-2/480/480",
  },
  {
    id: "asset-woodland",
    name: "Ethereal Woodlands",
    category: "Photography",
    creator: "Marcus Aurel",
    likes: 2310,
    description: "Mist-heavy landscape photography tuned for journal covers.",
    image: "https://picsum.photos/seed/litenote-asset-3/480/660",
  },
  {
    id: "asset-amber",
    name: "Amber Wash 04",
    category: "Texture",
    creator: "Sarah Jenkins",
    likes: 3094,
    description: "Warm watercolor overlay used by the featured workshop preset.",
    image: "https://picsum.photos/seed/litenote-asset-4/480/480",
  },
];

const workshopPresets: WorkshopPreset[] = [
  {
    id: "preset-vintage",
    name: "Vintage Letter",
    tagline: "Paper grain with restrained serif hierarchy",
    summary: "A tactile editorial preset inspired by the reference workshop panel.",
    cssSnippet: [
      ".entry-card {",
      "  background: linear-gradient(180deg, #f6f2e8 0%, #efe7d7 100%);",
      "  border-radius: 28px;",
      "  box-shadow: 0 20px 60px rgba(39, 31, 23, 0.12);",
      "}",
      "",
      ".entry-card h1 {",
      "  font-family: 'Iowan Old Style', 'Times New Roman', serif;",
      "  color: #3d4436;",
      "  letter-spacing: -0.03em;",
      "}",
    ].join("\n"),
    quote: "The memory of a dream is as fragile as the wings of a moth.",
  },
  {
    id: "preset-atlas",
    name: "Modern Atlas",
    tagline: "Magazine framing for field notes and travel stories",
    summary: "Wide margins, numbered dividers, and understated utility labels.",
    cssSnippet: [
      ".layout-shell {",
      "  display: grid;",
      "  grid-template-columns: 96px 1fr 320px;",
      "  gap: 24px;",
      "}",
      "",
      ".utility-label {",
      "  font-size: 11px;",
      "  text-transform: uppercase;",
      "  letter-spacing: 0.18em;",
      "}",
    ].join("\n"),
    quote: "Design quietly guides the eye before the words even begin.",
  },
];

const notes: Note[] = [
  {
    id: "note-alps",
    title: "The Quiet Morning in the Alps",
    body: [
      "There is a silence here that feels ancient. Not the silence of emptiness, but the deep, resonant quiet of stone and ice.",
      "",
      "The light moves slowly over the ridge line, and each shift changes how I remember the day. I want LiteNote to feel like this: tactile, calm, and deliberate.",
      "",
      "Action items:",
      "- refine the editorial hero",
      "- connect templates to saved notes",
      "- make the workshop preset feel alive",
    ].join("\n"),
    summary: "Morning field note exploring the new editorial journal direction.",
    tags: ["travel", "reflection", "design"],
    mood: "reflective",
    templateId: "botanical-reflection",
    coverImage: "https://picsum.photos/seed/litenote-note-1/960/720",
    isFavorite: true,
    isArchived: false,
    status: "published",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "note-sprint",
    title: "Weekly Build Sprint",
    body: [
      "Ship the new journal shell, verify API persistence, and tighten the asset browsing story.",
      "",
      "Need a tighter save flow: edits should stay local while typing, then sync cleanly when saved.",
    ].join("\n"),
    summary: "Working note for the rebuild sprint and delivery checklist.",
    tags: ["product", "roadmap"],
    mood: "focused",
    templateId: "monochrome-focus",
    coverImage: "https://picsum.photos/seed/litenote-note-2/960/720",
    isFavorite: false,
    isArchived: false,
    status: "draft",
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "note-light",
    title: "Golden Hour Reference Board",
    body: [
      "Collected a warmer palette for welcome screens and featured cards.",
      "",
      "This one should lean optimistic rather than nostalgic.",
    ].join("\n"),
    summary: "Palette study for the discover surface and mood-driven hero art.",
    tags: ["palette", "inspiration"],
    mood: "bright",
    templateId: "golden-hour",
    coverImage: "https://picsum.photos/seed/litenote-note-3/960/720",
    isFavorite: true,
    isArchived: false,
    status: "draft",
    createdAt: now(),
    updatedAt: now(),
  },
];

export const createSeedDatabase = (): DatabaseShape => ({
  notes,
  templates,
  assets,
  workshopPresets,
});
